title: Pato Service
description: Documentación del servicio de Pato Service
theme: jekyll-theme-cayman

# Configuración importante para Jekyll
defaults:
  -
    scope:
      path: "" # aplica a todos los archivos
    values:
      layout: default

# Especificar que los archivos .md deben ser procesados
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Configurar la página principal
index_page: index.md 